### PR TITLE
Fix duplicate fullDayEvent

### LINKED ISSUE #59: Fix sending duplicate full day events to frontend
image

### PR DESCRIPTION
**Pull request by Danielsio**
Fixed bug of duplicate full day events Refer to #59
problem was that after Add full-day-events from DB the full day events list wasnt sorted, i applied a sort + rewrote the EventComparator to be more readable

close #59

if you are still afraid to merge this PR, please tell me and i will add more tests to prove the comparator is not broken.

### CODE REVIEW

File: src/main/java/com/example/planit/engine/CalendarEngine.java [hunk 1]
```diff
@@ -1318,10 +1320,9 @@ private List<Event> removeDuplicationsByDate(List<Event> fullDayEvents) {
             if (lastEventInModifiedList == null || lastEventInModifiedList.getStart().getDate().getValue() != fullDayEvent.getStart().getDate().getValue()) {
                 lastEventInModifiedList = fullDayEvent;
                 modifiedFullDayEventsList.add(lastEventInModifiedList);
-            } else {
+            } else if (!lastEventInModifiedList.getSummary().equals(fullDayEvent.getSummary())) {
                 lastEventInModifiedList.setSummary(lastEventInModifiedList.getSummary() + " | " + fullDayEvent.getSummary());
             }
```
Comment (itayf9) [inline src/main/java/com/example/planit/engine/CalendarEngine.java:1326]: @Danielsio Add some documentation explaining the else case being ignored.

**Review by itayf9 — CHANGES_REQUESTED** [review]

**Review by oshriFadlon1 — APPROVED** [review]

**Review by itayf9 — APPROVED** [review]
Great work Daniel! All good.
