### PR TITLE
Fix break time in the start of each user event

### LINKED ISSUE #65: Add a space before user events
Add space before each event in the function getFreeSlot like the function addBreakTimeInEndOfEachUserEvent 

1. create new function 
2. extract the start time of each free slot set the time half hour back.

### PR DESCRIPTION
**Pull request by oshriFadlon1**
1.I add new function addBreakTimeInStartOfEachUserEvent.
it adds break time in start of each user event.
it is same as the function addBreakTimeInEndOfEachUserEvent.

as you can see in the picture, the event in the 7(mon) amd the event in the 8(tue) show the fix of the issue we have in #65 

close #65 

image

### CODE REVIEW

**Comment by Danielsio** [comment]
can you explain why i see 4 commits in this PR please ?

File: src/main/java/com/example/planit/engine/CalendarEngine.java [hunk 1]
```diff
@@ -399,6 +399,8 @@ private static DTOfreetime getFreeSlots(List<Event> userEvents, User user, List<
 
         // add to the end of each user event a break
         addBreakTimeInEndOfEachUserEvent(userEvents, user.getUserPreferences().getUserBreakTime());
+        // add to the start of each user event a break
+        addBreakTimeInStartOfEachUserEvent(userEvents, user.getUserPreferences().getUserBreakTime());
         // get the free slot before the first event
```
Comment (Danielsio) [inline src/main/java/com/example/planit/engine/CalendarEngine.java:401]: make it one single function call please for both start and end breaks.

File: src/main/java/com/example/planit/utill/Constants.java [hunk 2]
```diff
@@ -10,7 +10,7 @@ public class Constants {
 
     public static final long MINUTES_TO_MILLIS = 60000;
 
-    public static final int HOUR_IN_MINUTES = 60;
+    public static final int MINUTES_IN_SECONEDS = 60;
```
Comment (Danielsio) [inline src/main/java/com/example/planit/utill/Constants.java:14]: did you mean MINUTE here ? if so please rename this one.

File: src/test/java/com/example/planit/engine/calendar/PlanITApplicationTests.java [hunk 3]
```diff
@@ -183,4 +184,24 @@ void RegeneratePlan() {
...
+                "2023-08-06T00:00:00.000Z",
+                "2023-08-12T21:59:59.000Z",
+                decisions);
+
+        if (scanResponse.isSucceed()) {
+            DTOscanResponseToController regeneratePlanResponse = calendarEngine.regenerateStudyPlan(
+                    subjectIDForTestInput,
+                    decisions,
+                    Instant.parse("2023-08-06T22:00:00.000Z").plus(1, ChronoUnit.DAYS));
+
```
Comment (Danielsio) [inline src/test/java/com/example/planit/engine/calendar/PlanITApplicationTests.java:201]: since you can do `Instant.parse("2023-08-06T22:00:00.000Z")` and put there any string you want with valid iso format you dont need to add `.plus(1, ChronoUnit.DAYS));`

just put the value you want and that's it => `Instant.parse("2023-08-07T22:00:00.000Z")`

File: src/main/java/com/example/planit/engine/CalendarEngine.java [hunk 4]
```diff
@@ -1414,6 +1416,23 @@ private static void addBreakTimeInEndOfEachUserEvent(List<Event> userEvents, int
...
+     * add break in the start of each user event in the list
+     *
+     * @param userEvents    list of all the {@link Event} the user have in the calendars
+     * @param userBreakTime the break time in user preferences in minutes
+     */
+    private static void addBreakTimeInStartOfEachUserEvent(List<Event> userEvents, int userBreakTime) {
+
+        for (Event currentUserEvent : userEvents) {
+            Instant oldStartOfUserEvent = Instant.ofEpochMilli(currentUserEvent.getStart().getDateTime().getValue());
+            Instant newStartOfUserEvent = oldStartOfUserEvent.minusSeconds(2L * userBreakTime * MINUTES_IN_SECONEDS);
```
Comment (Danielsio) [inline src/main/java/com/example/planit/engine/CalendarEngine.java]: Rename `oldStartOfUserEvent` to `oldStartTimeOfUserEvent`

File: src/main/java/com/example/planit/engine/CalendarEngine.java [hunk 5]
```diff
@@ -1414,6 +1416,23 @@ private static void addBreakTimeInEndOfEachUserEvent(List<Event> userEvents, int
...
+            currentUserEvent.setStart(new EventDateTime()
```
Comment (Danielsio) [inline src/main/java/com/example/planit/engine/CalendarEngine.java:1415]: `Instant newStartOfUserEvent = oldStartOfUserEvent.minusSeconds(2L * userBreakTime * MINUTES_IN_SECONEDS);`

why are you giving a break of (2 * userBreakTime) ?
if userBreakTime is big like 60 minutes it would create a window of 2 hours between each event. you sure that is what you want ? 

i dont mind but i believe somewhere we did something similar with Math.max(60, 2 * userBreakTime)
maybe it should be placed here as well

**Review by Danielsio — CHANGES_REQUESTED** [review]
Nice work Oshri, Left some small comments.

File: src/main/java/com/example/planit/engine/CalendarEngine.java [hunk 6]
```diff
@@ -398,7 +398,8 @@ private static DTOfreetime getFreeSlots(List<Event> userEvents, User user, List<
         List<TimeSlot> userFreeTimeSlots = new ArrayList<>();
 
         // add to the end of each user event a break
-        addBreakTimeInEndOfEachUserEvent(userEvents, user.getUserPreferences().getUserBreakTime());
+        // add to the start of each user event a break
+        addBreakTimeInStartAndEndOfEachUserEvent(userEvents, user.getUserPreferences().getUserBreakTime());
```
Comment (Danielsio) [inline src/main/java/com/example/planit/engine/CalendarEngine.java:400]: docs says exactly the name of the fucntion, remove it please.

File: src/test/java/com/example/planit/engine/calendar/PlanITApplicationTests.java [hunk 7]
```diff
@@ -11,6 +11,7 @@
 import org.springframework.test.context.junit.jupiter.SpringExtension;
 
 import java.time.Instant;
+import java.time.temporal.ChronoUnit;
 import java.util.HashMap;
```
Comment (Danielsio) [inline src/test/java/com/example/planit/engine/calendar/PlanITApplicationTests.java]: do you still need this import ?

**Review by Danielsio — APPROVED** [review]
Good work

File: src/main/java/com/example/planit/engine/CalendarEngine.java [hunk 8]
```diff
@@ -1398,16 +1397,24 @@ private StudySession getUpComingSessionForUser(User user) throws GeneralSecurity
...
-    private static void addBreakTimeInEndOfEachUserEvent(List<Event> userEvents, int userBreakTime) {
+    private static void addBreakTimeInStartAndEndOfEachUserEvent(List<Event> userEvents, int userBreakTime) {
 
         for (Event currentUserEvent : userEvents) {
-            Instant oldEndOfUserEvent = Instant.ofEpochMilli(currentUserEvent.getEnd().getDateTime().getValue());
-            Instant newEndOfUserEvent = oldEndOfUserEvent.plus(Math.min(2 * userBreakTime, SPACE_LIMIT_BETWEEN_EVENTS), ChronoUnit.MINUTES);
+            // add break in the end of the current event
+            Instant oldEndTimeOfUserEvent = Instant.ofEpochMilli(currentUserEvent.getEnd().getDateTime().getValue());
+            Instant newEndOfUserEvent = oldEndTimeOfUserEvent.plus(Math.min(2 * userBreakTime, SPACE_LIMIT_BETWEEN_EVENTS), ChronoUnit.MINUTES);
+            // add break in the start of the current event
```
Comment (Danielsio) [inline src/main/java/com/example/planit/engine/CalendarEngine.java:1411]: Rename to newEndTimeOfUserEvent please

File: src/main/java/com/example/planit/engine/CalendarEngine.java [hunk 9]
```diff
@@ -1398,16 +1397,24 @@ private StudySession getUpComingSessionForUser(User user) throws GeneralSecurity
...
+            Instant oldStartTimeOfUserEvent = Instant.ofEpochMilli(currentUserEvent.getStart().getDateTime().getValue());
+            Instant newStartOfUserEvent = oldStartTimeOfUserEvent.minusSeconds(Math.min(2L * userBreakTime * MINUTE_IN_SECONEDS, SPACE_LIMIT_BETWEEN_EVENTS * MINUTE_IN_SECONEDS));
```
Comment (itayf9) [inline src/main/java/com/example/planit/engine/CalendarEngine.java]: rename the `Instant` `newStartOfUserEvent` to `newStartTimeOfUserEvent`, or remove the "time" from `oldStartTimeOfUserEvent`.

>

File: src/main/java/com/example/planit/engine/CalendarEngine.java (hunk 8 above)
Comment (itayf9) [reply src/main/java/com/example/planit/engine/CalendarEngine.java:1411]: Or remove the "time" from `oldEndTimeOfUserEvent`. So it will be consistant.
I prefer the option including the "time" in the variables' names

File: src/main/java/com/example/planit/utill/Constants.java (hunk 2 above)
Comment (itayf9) [reply src/main/java/com/example/planit/utill/Constants.java:14]: You have a typo in "SECONDS" (you wrote "SECONEDS").
Also, ` MINUTE_IN_SECONEDS` is not so readable. Because the word "in" should not be used like that ( it sounds like you have a minute inside the seconds. At first I didn't understand what this constant represents.
I think you meant "SECONDS_IN_A_MINUTE", or "MINUTE_AS_SECONDS".

File: src/main/java/com/example/planit/utill/Constants.java [hunk 10]
```diff
@@ -10,7 +10,7 @@ public class Constants {
 
     public static final long MINUTES_TO_MILLIS = 60000;
 
-    public static final int HOUR_IN_MINUTES = 60;
+    public static final int MINUTE_IN_SECONEDS = 60;
 
     public static final int SPACE_LIMIT_BETWEEN_EVENTS = 60;
```
Comment (itayf9) [inline src/main/java/com/example/planit/utill/Constants.java]: If you can add the measure unit to the constant name it would be nice.
`SPACE_LIMIT_BETWEEN_EVENTS` in seconds? minutes?

**Review by itayf9 — CHANGES_REQUESTED** [review]

**Review by itayf9 — APPROVED** [review]
Good job Oshri!
